import assert from "node:assert/strict";import test from "node:test";
import { LEGAL_BRANCHES, LEGAL_BRANCH_GATE, transitionLifecycle } from "../src/trademark-lifecycle.js";
const start={stage:"LEAD_INTAKE" as const,monitoringActive:true,commercialStatus:"CURRENT" as const};
test("covers every contentious and petition branch with human gates",()=>{assert.equal(LEGAL_BRANCHES.length,12);for(const b of LEGAL_BRANCHES)assert.deepEqual(LEGAL_BRANCH_GATE[b],{analysisDraftAllowed:true,humanLegalApprovalRequired:true,customerConfirmationRequired:true,procuradorOfficialClickRequired:true})});
test("forces ordered lifecycle and official human gate",()=>{assert.equal(transitionLifecycle(start,{type:"ADVANCE",targetStage:"QUALIFICATION"}).requiresOfficialActGate,false);assert.throws(()=>transitionLifecycle(start,{type:"ADVANCE",targetStage:"FILING_HUMAN_PROTOCOL"}),/INVALID_LIFECYCLE_TRANSITION/)});
test("RPI event opens legal review, never automated legal judgment",()=>{const r=transitionLifecycle({...start,stage:"RPI_MONITORING"},{type:"RPI_EVENT",legalBranch:"OPPOSITION"});assert.equal(r.requiresHumanLegalReview,true);assert.equal(r.legalBranch,"OPPOSITION")});
test("delinquency blocks new official acts but preserves state",()=>{const c={...start,stage:"GRU_CUSTOMER_CONFIRMATION" as const,commercialStatus:"PAST_DUE" as const};assert.throws(()=>transitionLifecycle(c,{type:"ADVANCE",targetStage:"GRU_HUMAN_ISSUANCE"}),/COMMERCIAL_STATUS/)});
test("cancellation stops monitoring; reactivation restores billing state only",()=>{const cancelled=transitionLifecycle(start,{type:"CANCEL"});assert.equal(cancelled.monitoringActive,false);assert.equal(transitionLifecycle(cancelled,{type:"REACTIVATE"}).monitoringActive,false)});

import { TRADEMARK_STAGES, validateCompletion } from "../src/trademark-lifecycle.js";
test("lifecycle reaches certificate delivery, post-grant watch and renewal",()=>{for(const s of ["CERTIFICATE_PENDING","CERTIFICATE_ISSUED","CERTIFICATE_DELIVERED","POST_GRANT_MONITORING","RENEWAL_NOTICE","RENEWAL_FEE_PREVIEW","RENEWAL_HUMAN_PAYMENT","RENEWED"])assert.ok(TRADEMARK_STAGES.includes(s as never))});
test("completion requires WhatsApp customer journey, certificate and final dossier",()=>{assert.deepEqual(validateCompletion({customerChannel:"WHATSAPP",customerTouchpoints:["DOCUMENTS","ACCEPTANCE","SIGNATURE","PAYMENT","DECISION"],dedicatedProcuradorAtOfficialActs:true,legalStrategyHumanApproved:true,officialReceiptRequired:true,certificateDelivered:true,finalDossierDelivered:true}),[]);const e=validateCompletion({customerChannel:"WHATSAPP",customerTouchpoints:[],dedicatedProcuradorAtOfficialActs:true,legalStrategyHumanApproved:true,officialReceiptRequired:true,certificateDelivered:false,finalDossierDelivered:false});assert.ok(e.includes("CERTIFICATE_NOT_DELIVERED"));assert.ok(e.includes("FINAL_DOSSIER_NOT_DELIVERED"))});
test("renewal official payment requires the official-act gate",()=>{let c={stage:"RENEWAL_CUSTOMER_CONFIRMATION" as const,monitoringActive:true,commercialStatus:"CURRENT" as const};assert.equal(transitionLifecycle(c,{type:"ADVANCE",targetStage:"RENEWAL_HUMAN_PAYMENT"}).requiresOfficialActGate,true)});

import { advanceProceduralCase, evidenceRequiredForFiling, PROCEDURAL_WORKFLOW } from "../src/trademark-lifecycle.js";
test("procedural flow preserves deadline, strategy, evidence, approval, legal review, filing and receipt",()=>{assert.deepEqual(PROCEDURAL_WORKFLOW,["RPI_DETECTED","DEADLINE_VERIFIED","PLAIN_LANGUAGE_RISK_EXPLAINED","STRATEGY_PROPOSED","EVIDENCE_REQUESTED","EVIDENCE_COMPLETE","DRAFT_PREPARED","CUSTOMER_SUMMARY_DELIVERED","CUSTOMER_APPROVED","APPLICABLE_FEE_PAID","HUMAN_LEGAL_APPROVED","PROCURADOR_FILED","OFFICIAL_RECEIPT_DELIVERED","OUTCOME_MONITORING"])});
test("cannot explain risk before deadline verification or skip legal review",()=>{const c={branch:"MERIT_REQUIREMENT" as const,step:"DEADLINE_VERIFIED" as const,deadlineVerified:false,feeApplicable:true};assert.throws(()=>advanceProceduralCase(c,"PLAIN_LANGUAGE_RISK_EXPLAINED"),/DEADLINE/);assert.throws(()=>advanceProceduralCase({...c,step:"CUSTOMER_APPROVED",deadlineVerified:true},"HUMAN_LEGAL_APPROVED"),/INVALID_PROCEDURAL_TRANSITION/)});
test("filing evidence reports every missing gate explicitly",()=>{const e=evidenceRequiredForFiling({branch:"APPEAL",step:"CUSTOMER_APPROVED",deadlineVerified:true,feeApplicable:true});assert.deepEqual(e,["FEE_PAYMENT_MISSING","HUMAN_LEGAL_APPROVAL_MISSING","PROCURADOR_FILING_MISSING","OFFICIAL_RECEIPT_MISSING"])});
test("all named legal branches use the same controlled procedural chain",()=>{for(const branch of LEGAL_BRANCHES){const c={branch,step:"RPI_DETECTED" as const,deadlineVerified:true,feeApplicable:false};assert.equal(advanceProceduralCase(c,"DEADLINE_VERIFIED").branch,branch)}});
