import {test,expect} from '@playwright/test';
const open=async(page,width=390)=>{await page.setViewportSize({width,height:900});await page.goto('/admin-preview');await expect(page.getByRole('heading',{name:/O que pede/})).toBeVisible();};
const chat=async(page,width=430)=>{await open(page,width);const nav=width<780?page.locator('.nx-bottom'):page.locator('.nx-rail');await nav.getByRole('button',{name:'Conversas'}).click();if(width<780)await page.getByRole('button',{name:/Marina · Ateliê Marea/}).click();await expect(page.getByText('Meta direto · offline nesta prévia')).toBeVisible();};
for(const width of [390,430,1440])test(`frozen v2 home ${width}`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page,width);await expect(page.getByText(/Contagens fictícias/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);});
test('command routes to frozen process map',async({page})=>{await open(page);await page.getByRole('button',{name:/Pergunte à operação/}).click();await page.getByPlaceholder('Pergunte ou comande a operação…').fill('mapa');await page.getByRole('button',{name:/Abra o mapa/}).click();await expect(page.getByRole('heading',{name:/Cada marca/})).toBeVisible();});
for(const width of [390,430,1440])test(`v3 conversation workspace ${width}`,async({page},info)=>{await chat(page,width);await expect(page.getByText('LEITURA VIVA · REG')).toBeVisible();await expect(page.getByText('INTENÇÃO DETECTADA')).toBeVisible();await expect(page.getByText('ÁUDIO ENTENDIDO')).toBeVisible();await expect(page.getByText('DOCUMENTO INTERPRETADO')).toBeVisible();await expect(page.getByText('PRÓXIMA DECISÃO')).toBeVisible();await expect(page.getByText(/Envio e atos oficiais indisponíveis/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:info.outputPath(`conversation-v3-${width}.png`),fullPage:width>=780});});
test('intelligence tabs, evidence sheet and proactive composer work locally',async({page},info)=>{await chat(page,430);await page.locator('.nx-intelligence-strip button').nth(1).click();await expect(page.locator('.nx-live-path')).toContainText('Viabilidade');await page.locator('.nx-intelligence-strip button').nth(2).click();await expect(page.getByText('fontes oficiais')).toBeVisible();await page.getByRole('button',{name:/Abrir cofre/}).click();await expect(page.getByRole('dialog',{name:'Raciocínio e fontes'})).toContainText('Nenhuma busca real');await page.getByRole('button',{name:'Entendi'}).click();await page.getByRole('button',{name:/Sugerir próximo passo/}).click();await expect(page.getByText('RASCUNHO SUGERIDO · NÃO ENVIADO')).toBeVisible();await page.screenshot({path:info.outputPath('conversation-composer-430.png'),fullPage:false});});
test('human takeover is explicit and reversible',async({page})=>{await chat(page,1440);await page.getByRole('button',{name:'Assumir'}).click();await expect(page.getByText('Davilys no controle')).toBeVisible();await expect(page.getByRole('button',{name:/Devolver à Reg/})).toBeVisible();});
test('direct Meta boundary and project isolation remain explicit',async({page})=>{await open(page);await page.locator('.nx-bottom').getByRole('button',{name:'Mais'}).click();await expect(page.getByText('Arquitetura direta, conexão ausente')).toBeVisible();await expect(page.getByText(/abstração Meta direta e isolada/)).toBeVisible();});
