-- RegistreAi reference data seed\n-- Generated from the live Supabase project. Contains no customer data or secrets.\n\nINSERT INTO public.plans(code,name,setup_fee_cents,monthly_fee_cents,unlimited_marks,resources_included,guarantee_included,active,public_description) VALUES ('ILIMITADO','Ilimitado',49700,59900,true,true,true,true,'Honorários de registros ilimitados para o mesmo CPF ou CNPJ titular do plano. Sem carência e cancelamento quando quiser. Não permite terceiros. Taxas oficiais do INPI à parte.') ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,setup_fee_cents=EXCLUDED.setup_fee_cents,monthly_fee_cents=EXCLUDED.monthly_fee_cents,unlimited_marks=EXCLUDED.unlimited_marks,resources_included=EXCLUDED.resources_included,guarantee_included=EXCLUDED.guarantee_included,active=EXCLUDED.active,public_description=EXCLUDED.public_description;
INSERT INTO public.plans(code,name,setup_fee_cents,monthly_fee_cents,unlimited_marks,resources_included,guarantee_included,active,public_description) VALUES ('PROTECAO','Proteção',19700,4900,false,true,true,true,'Uma marca, do início ao fim, sem fidelidade. Adesão cobre busca de viabilidade após contratação/pagamento e preparação do protocolo. Taxas oficiais do INPI à parte.') ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,setup_fee_cents=EXCLUDED.setup_fee_cents,monthly_fee_cents=EXCLUDED.monthly_fee_cents,unlimited_marks=EXCLUDED.unlimited_marks,resources_included=EXCLUDED.resources_included,guarantee_included=EXCLUDED.guarantee_included,active=EXCLUDED.active,public_description=EXCLUDED.public_description;

INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('appeal','archived',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('appeal','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('appeal','granted',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('appeal','monitoring',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('appeal','refused',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_customer_confirmation','awaiting_inpi_fee',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_customer_confirmation','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_customer_confirmation','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_customer_confirmation','viability',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_inpi_fee','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_inpi_fee','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_inpi_fee','ready_to_file',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_setup_payment','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_setup_payment','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('awaiting_setup_payment','viability',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('contracting','awaiting_setup_payment',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('contracting','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filed','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filed','granted',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filed','monitoring',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filed','office_action',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filed','opposition',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filed','refused',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filing','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('filing','filed',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('granted','archived',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('granted','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('granted','expired',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('granted','monitoring',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('intake','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('intake','contracting',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','archived',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','expired',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','granted',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','office_action',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','opposition',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('monitoring','refused',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('office_action','archived',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('office_action','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('office_action','monitoring',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('office_action','refused',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('opposition','archived',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('opposition','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('opposition','monitoring',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('opposition','refused',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('ready_to_file','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('ready_to_file','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('ready_to_file','filing',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('refused','appeal',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('refused','archived',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('refused','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('viability','awaiting_customer_confirmation',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('viability','cancelled',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;
INSERT INTO public.process_transition_rules(from_status,to_status,active) VALUES ('viability','error_hold',true) ON CONFLICT (from_status,to_status) DO UPDATE SET active=EXCLUDED.active;

INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('3000','Recurso contra indeferimento de pedido de registro de marca - valor por classe','MARKS','CLASS',70000,35000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('3015','Contrarrazões ao recurso/nulidade','MARKS','SERVICE',18000,9000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('3016','Cumprimento de exigência em grau de recurso/nulidade','MARKS','SERVICE',18000,9000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('3022','Oposição com restrição de alegações - valor por classe','MARKS','CLASS',36000,18000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('332','Oposição - valor por classe','MARKS','CLASS',52000,26000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('338','Cumprimento de exigência decorrente de exame formal em pedido de registro','MARKS','SERVICE',18000,9000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('339','Manifestação','MARKS','SERVICE',18000,9000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('340','Cumprimento de exigência','MARKS','SERVICE',18000,9000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('372','Primeiro decênio e expedição do certificado - prazo ordinário','MARKS','CLASS',0,0,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('374','Prorrogação do registro e expedição do certificado - prazo ordinário','MARKS','CLASS',100000,50000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('382','Cumprimento de exigência decorrente de exame de conformidade em petição','MARKS','SERVICE',18000,9000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('389','Pedido de registro de marca com especificação pré-aprovada','MARKS','CLASS',88000,44000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.inpi_fee_catalog(service_code,service_name,scope,billing_unit,standard_amount_cents,discount50_amount_cents,effective_from,effective_to,source_version,source_url,active) VALUES ('394','Pedido de registro de marca com especificação de livre preenchimento','MARKS','CLASS',172000,86000,'2025-08-07',NULL,'Portaria GM/MDIC nº 110/2025 + tabela atualizada em 20/12/2025','https://www.gov.br/inpi/pt-br/servicos/custos-e-pagamento/NovaTabeladeRetribuiesINPI_MARCAS_Final_20_dez_25.pdf',true) ON CONFLICT (service_code,effective_from) DO UPDATE SET service_name=EXCLUDED.service_name,scope=EXCLUDED.scope,billing_unit=EXCLUDED.billing_unit,standard_amount_cents=EXCLUDED.standard_amount_cents,discount50_amount_cents=EXCLUDED.discount50_amount_cents,effective_to=EXCLUDED.effective_to,source_version=EXCLUDED.source_version,source_url=EXCLUDED.source_url,active=EXCLUDED.active;

INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-01-01','Confraternização Universal','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-01-20','Dia de São Sebastião - Rio de Janeiro/RJ','INPI_RJ','https://www.gov.br/inpi/pt-br/central-de-conteudo/legislacao/arquivos/documentos/2025pr-45-feriados-e-estabelece-os-dias-de-ponto-facultativo-regionais-no-ano-de-2026.pdf/@@download/file',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-02-16','Carnaval','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-02-17','Carnaval','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-04-03','Paixão de Cristo','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-04-20','Ponto facultativo','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-04-21','Tiradentes','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-04-23','Dia de São Jorge - Rio de Janeiro/RJ','INPI_RJ','https://www.gov.br/inpi/pt-br/central-de-conteudo/legislacao/arquivos/documentos/2025pr-45-feriados-e-estabelece-os-dias-de-ponto-facultativo-regionais-no-ano-de-2026.pdf/@@download/file',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-05-01','Dia Mundial do Trabalho','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-06-04','Corpus Christi','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-06-05','Ponto facultativo','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-09-07','Independência do Brasil','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-10-12','Nossa Senhora Aparecida','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-10-28','Dia do Servidor Público federal','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-11-02','Finados','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-11-15','Proclamação da República','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-11-20','Dia Nacional de Zumbi e da Consciência Negra','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;
INSERT INTO public.inpi_non_working_days(day,name,scope,source_url,verified) VALUES ('2026-12-25','Natal','FEDERAL','https://legis.sigepe.gov.br/sigepe-bgp-ws-legis/legis-service/download/?id=0026440285-ALPDF/2025',true) ON CONFLICT (day) DO UPDATE SET name=EXCLUDED.name,scope=EXCLUDED.scope,source_url=EXCLUDED.source_url,verified=EXCLUDED.verified;

INSERT INTO public.inpi_calendar_years(year,verified,source_name,source_url,verified_at,notes) VALUES (2026,true,'Portaria MGI nº 11.460/2025 + Portaria Normativa INPI/PR nº 45/2026','https://www.gov.br/inpi/pt-br/central-de-conteudo/legislacao/arquivos/documentos/2025pr-45-feriados-e-estabelece-os-dias-de-ponto-facultativo-regionais-no-ano-de-2026.pdf/@@download/file','2026-09-21 05:51:32.641843+00','Inclui feriados/pontos facultativos federais de dia inteiro e feriados regionais da sede do INPI no Rio de Janeiro. Datas de expediente parcial não são tratadas como dia integralmente não útil.') ON CONFLICT (year) DO UPDATE SET verified=EXCLUDED.verified,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,verified_at=EXCLUDED.verified_at,notes=EXCLUDED.notes;

INSERT INTO public.deadline_rules(event_type,legal_window_days,start_rule,continuous_days,extend_due_if_non_working,source_name,source_url,active) VALUES ('FORMAL_REQUIREMENT',5,'FIRST_BUSINESS_DAY_AFTER_PUBLICATION',true,true,'Manual de Marcas - Exame formal','https://manualdemarcas.inpi.gov.br/projects/manual-de-marcas-3-edicao-6-revisao-20-08-2024/wiki/04_Exame_formal',true) ON CONFLICT (event_type) DO UPDATE SET legal_window_days=EXCLUDED.legal_window_days,start_rule=EXCLUDED.start_rule,continuous_days=EXCLUDED.continuous_days,extend_due_if_non_working=EXCLUDED.extend_due_if_non_working,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.deadline_rules(event_type,legal_window_days,start_rule,continuous_days,extend_due_if_non_working,source_name,source_url,active) VALUES ('MERIT_REQUIREMENT',60,'FIRST_BUSINESS_DAY_AFTER_PUBLICATION',true,true,'LPI / Manual de Marcas - prazos','https://manualdedi.inpi.gov.br/projects/manual-de-marcas-3-edicao-6-revisao-20-08-2024/wiki/01_Disposições_gerais',true) ON CONFLICT (event_type) DO UPDATE SET legal_window_days=EXCLUDED.legal_window_days,start_rule=EXCLUDED.start_rule,continuous_days=EXCLUDED.continuous_days,extend_due_if_non_working=EXCLUDED.extend_due_if_non_working,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.deadline_rules(event_type,legal_window_days,start_rule,continuous_days,extend_due_if_non_working,source_name,source_url,active) VALUES ('OPPOSITION',60,'FIRST_BUSINESS_DAY_AFTER_PUBLICATION',true,true,'Manual de Marcas - Oposição/manifestação','https://manualdemarcas.inpi.gov.br/projects/manual-de-marcas-3-edicao-6-revisao-20-08-2024/wiki/03_Como_formular_pedido_de_registro_ou_petição_de_marca',true) ON CONFLICT (event_type) DO UPDATE SET legal_window_days=EXCLUDED.legal_window_days,start_rule=EXCLUDED.start_rule,continuous_days=EXCLUDED.continuous_days,extend_due_if_non_working=EXCLUDED.extend_due_if_non_working,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,active=EXCLUDED.active;
INSERT INTO public.deadline_rules(event_type,legal_window_days,start_rule,continuous_days,extend_due_if_non_working,source_name,source_url,active) VALUES ('REFUSAL',60,'FIRST_BUSINESS_DAY_AFTER_PUBLICATION',true,true,'LPI / Manual de Marcas - recurso','https://manualdemarcas.inpi.gov.br/',true) ON CONFLICT (event_type) DO UPDATE SET legal_window_days=EXCLUDED.legal_window_days,start_rule=EXCLUDED.start_rule,continuous_days=EXCLUDED.continuous_days,extend_due_if_non_working=EXCLUDED.extend_due_if_non_working,source_name=EXCLUDED.source_name,source_url=EXCLUDED.source_url,active=EXCLUDED.active;

INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('ASAAS',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;
INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('EMAIL',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;
INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('HOSTINGER',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;
INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('INPI',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;
INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('OPENAI',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;
INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('RPI',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;
INSERT INTO public.integration_status(provider,enabled,environment,health_status,config_redacted) VALUES ('WHATSAPP_META',false,'sandbox','unconfigured','{}'::jsonb) ON CONFLICT (provider) DO NOTHING;

-- Durable queues

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pgmq.list_queues() WHERE queue_name='reg_jobs') THEN PERFORM pgmq.create('reg_jobs'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pgmq.list_queues() WHERE queue_name='notifications') THEN PERFORM pgmq.create('notifications'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pgmq.list_queues() WHERE queue_name='inpi_jobs') THEN PERFORM pgmq.create('inpi_jobs'); END IF;
  IF NOT EXISTS (SELECT 1 FROM pgmq.list_queues() WHERE queue_name='legal_jobs') THEN PERFORM pgmq.create('legal_jobs'); END IF;
END $$;

-- Private storage bucket
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES ('registreai-private','registreai-private',false,52428800,ARRAY['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
ON CONFLICT (id) DO UPDATE SET public=false,file_size_limit=EXCLUDED.file_size_limit,allowed_mime_types=EXCLUDED.allowed_mime_types;

-- Scheduled jobs
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname='registreai_rpi_poll') THEN
    PERFORM cron.schedule('registreai_rpi_poll','17 */6 * * *', $cmd$select pgmq.send(''inpi_jobs'',''{"job_type":"rpi_poll"}''::jsonb,0);$cmd$);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname='registreai_deadline_sweep') THEN
    PERFORM cron.schedule('registreai_deadline_sweep','11 * * * *', $cmd$select pgmq.send(''legal_jobs'',''{"job_type":"deadline_sweep"}''::jsonb,0);$cmd$);
  END IF;
END $$;
