-- PREPARED ONLY. Do not apply before approved test-number setup.
CREATE TABLE IF NOT EXISTS public.whatsapp_channel_bindings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),phone_number_id text UNIQUE NOT NULL,waba_id text,environment text NOT NULL DEFAULT 'test' CHECK(environment IN('test','production')),enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.whatsapp_customer_state(phone_number_id text NOT NULL REFERENCES public.whatsapp_channel_bindings(phone_number_id),wa_id_hash text NOT NULL,workspace_id uuid REFERENCES public.workspaces(id) ON DELETE CASCADE,thread_id uuid REFERENCES public.conversation_threads(id) ON DELETE CASCADE,last_inbound_at timestamptz,customer_service_window_expires_at timestamptz,opted_out_at timestamptz,handoff_status text NOT NULL DEFAULT 'bot' CHECK(handoff_status IN('bot','requested','human')),memory_version bigint NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(phone_number_id,wa_id_hash));
CREATE TABLE IF NOT EXISTS public.whatsapp_message_status_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,phone_number_id text NOT NULL,provider_message_id text NOT NULL,status text NOT NULL CHECK(status IN('sent','delivered','read','failed','played','unknown')),provider_timestamp timestamptz,error_redacted jsonb NOT NULL DEFAULT '[]',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(phone_number_id,provider_message_id,status));
CREATE TABLE IF NOT EXISTS public.whatsapp_media_objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,provider_message_id text NOT NULL,provider_media_id text NOT NULL,message_type text NOT NULL CHECK(message_type IN('audio','image','document')),object_path text,mime_type text,sha256 text,size_bytes bigint,download_status text NOT NULL DEFAULT 'pending' CHECK(download_status IN('pending','stored','failed','expired')),encryption_nonce_b64 text,encryption_key_version integer,created_at timestamptz NOT NULL DEFAULT now(),downloaded_at timestamptz,UNIQUE(provider_message_id,provider_media_id));
ALTER TABLE public.whatsapp_channel_bindings ENABLE ROW LEVEL SECURITY;ALTER TABLE public.whatsapp_customer_state ENABLE ROW LEVEL SECURITY;ALTER TABLE public.whatsapp_message_status_events ENABLE ROW LEVEL SECURITY;ALTER TABLE public.whatsapp_media_objects ENABLE ROW LEVEL SECURITY;
INSERT INTO storage.buckets(id,name,public,file_size_limit)VALUES('whatsapp-media-private','whatsapp-media-private',false,104857600)ON CONFLICT(id)DO UPDATE SET public=false;

-- Explicit Data API grants (Supabase stops auto-granting new public tables on 2026-10-30).
GRANT SELECT, INSERT, UPDATE, DELETE ON public.whatsapp_channel_bindings, public.whatsapp_customer_state, public.whatsapp_message_status_events, public.whatsapp_media_objects TO service_role;
